baseURL = "https://yougotagift.com"
languageCode = "en-us"
title = "YOUGotaGift Tech Blog"
paginate = 50
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = ""

[params]
subtitle = "Technology blog of YOUGotaGift"

[taxonomies]
   tag = "tags"
   author = "authors"

[menu]
   [[menu.header]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

   [[menu.header]]
      identifier = "blog"
      name = "Engineering Blog"
      url = "/blog"
      weight = 2

   [[menu.header]]
      identifier = "stack"
      name = "Stack"
      url = "/stack"
      weight = 3
